### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by brindy** [brindy/map-reveal#5]
* Apply Apache 2.0 license header to each source file
* Add appropriate LICENSE files to the project

**Comment by Jaisimha-Kulkarni** [comment]
Can i take this?

**Comment by brindy** [comment]
All yours, thanks in advance!

**Comment by brindy** [comment]
Apologies @Jaisimha-Kulkarni - I didn't spot that @rblcoder had already done it!  You are too keen! Thanks anyway,
